#!/usr/bin/env bash

plaintext="./bin/plaintext.js"

function install {
    npm install
}

function build {
    npm run build
}

function watch {
    npm run watch
}

function format {
    npm run format
}

function publish {
    echo "[publish]" &&
        $plaintext toc src -o src/toc &&
        $plaintext dir src -o out/src &&
        $plaintext file README -o out/index.html --title "plaintext" &&
        $plaintext file AUTHORS -o out/AUTHORS.html --title "plaintext | AUTHORS" &&
        $plaintext file LICENSE -o out/LICENSE.html --title "plaintext | LICENSE" &&
        $plaintext toc docs/plaintextlife -o docs/plaintextlife/toc &&
        cat docs/plaintextlife/README <(echo) docs/plaintextlife/toc > docs/plaintextlife/index &&
        $plaintext dir docs/plaintextlife -o out/plaintextlife &&
        true
}

function serve {
    publish &&
        echo "[serve]" &&
        npx http-server out &&
        true
}

function t {
    test_prog_ext node test.js &&
        publish
}

function test_prog_ext {
    prog=$1
    ext=$2

    for file in $(find . | grep "^\./lib/" | grep "\.${ext}$")
    do
        echo ""
        echo "[test] $file"
        if ! time $prog $file
        then
            exit 1
        fi
    done
}

function main {
    for TASK in $@
    do
        $TASK
    done
}

main $@
