#!/usr/bin/env bash

plaintext="./bin/plaintext.js"

function install {
    yarn install
}

function build {
    yarn run build
}

function watch {
    yarn run watch
}

function format {
    yarn run format
}

function serve {
    echo "[serve]" &&
        $plaintext file AUTHORS --output out/AUTHORS.html &&
        $plaintext file LICENSE --output out/LICENSE.html &&
        $plaintext dir src \
                   --output out \
                   --index-title plaintext \
                   --index-prolog "$(cat README)" &&
        npx http-server out
}

function t {
    test_prog_ext node test.js
}

function test_prog_ext {
    prog=$1
    ext=$2

    for file in $(find . | grep "^\./lib/" | grep "\.${ext}$")
    do
        echo ""
        echo "[test] $file"
        if ! time $prog $file
        then
            exit 1
        fi
    done
}

function main {
    for TASK in $@
    do
        $TASK
    done
}

main $@
